# Generated by Django 3.2.8 on 2021-10-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_type', models.SmallIntegerField(default=1)),
                ('full_stack_seats', models.SmallIntegerField(default=3)),
                ('academic_seats', models.SmallIntegerField(default=3)),
                ('frontend_seats', models.SmallIntegerField(default=3)),
                ('backend_seats', models.SmallIntegerField(default=3)),
                ('task_capacity', models.SmallIntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('points', models.SmallIntegerField()),
                ('assigned', models.DateTimeField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('team_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev_tasks.team')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainBranch', models.CharField(max_length=100)),
                ('Employment', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('US_State', models.CharField(max_length=100)),
                ('UK_Country', models.CharField(max_length=100)),
                ('EdLevel', models.CharField(max_length=100)),
                ('Age1stCode', models.CharField(max_length=100)),
                ('LearnCode', models.CharField(max_length=100)),
                ('YearsCode', models.CharField(max_length=100)),
                ('YearsCodePro', models.CharField(max_length=100)),
                ('DevType', models.CharField(max_length=100)),
                ('OrgSize', models.CharField(max_length=100)),
                ('Currency', models.CharField(max_length=100)),
                ('CompTotal', models.CharField(max_length=100)),
                ('CompFreq', models.CharField(max_length=100)),
                ('LanguageHaveWorkedWith', models.CharField(max_length=100)),
                ('LanguageWantToWorkWith', models.CharField(max_length=100)),
                ('DatabaseHaveWorkedWith', models.CharField(max_length=100)),
                ('DatabaseWantToWorkWith', models.CharField(max_length=100)),
                ('PlatformHaveWorkedWith', models.CharField(max_length=100)),
                ('PlatformWantToWorkWith', models.CharField(max_length=100)),
                ('WebframeHaveWorkedWith', models.CharField(max_length=100)),
                ('WebframeWantToWorkWith', models.CharField(max_length=100)),
                ('MiscTechHaveWorkedWith', models.CharField(max_length=100)),
                ('MiscTechWantToWorkWith', models.CharField(max_length=100)),
                ('ToolsTechHaveWorkedWith', models.CharField(max_length=100)),
                ('ToolsTechWantToWorkWith', models.CharField(max_length=100)),
                ('NEWCollabToolsHaveWorkedWith', models.CharField(max_length=100)),
                ('NEWCollabToolsWantToWorkWith', models.CharField(max_length=100)),
                ('OpSys', models.CharField(max_length=100)),
                ('NEWStuck', models.CharField(max_length=100)),
                ('NEWSOSites', models.CharField(max_length=100)),
                ('SOVisitFreq', models.CharField(max_length=100)),
                ('SOAccount', models.CharField(max_length=100)),
                ('SOPartFreq', models.CharField(max_length=100)),
                ('SOComm', models.CharField(max_length=100)),
                ('NEWOtherComms', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Trans', models.CharField(max_length=100)),
                ('Sexuality', models.CharField(max_length=100)),
                ('Ethnicity', models.CharField(max_length=100)),
                ('Accessibility', models.CharField(max_length=100)),
                ('MentalHealth', models.CharField(max_length=100)),
                ('SurveyLength', models.CharField(max_length=100)),
                ('SurveyEase', models.CharField(max_length=100)),
                ('ConvertedCompYearly', models.CharField(max_length=100)),
                ('team_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev_tasks.team')),
            ],
        ),
    ]
